name: Build

on:
  push:
    branches: 
      - master
  pull_request:

jobs:
  build:
    name: Build
    strategy:
       matrix:
          java: [11]
          os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Build
        run: ./gradlew build
      - name: Store HTML test report
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-${{ matrix.java }}-test-report-html
          path: "**/reports/tests/"
      - name: Store XML test report
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-${{ matrix.java }}-test-results-xml
          path: "**/test-results/"




